import "./globals.css";

import { Metadata } from "next";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: {
    absolute: "", // in children, ignote template
    default: "kaszanka", // default for child 
    template: "|| %s || kasanka", // templat for children
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
        <Navbar />
        <div className="">{children}</div>
        <Footer />
      </body>
    </html> 
  );
}